config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "users/registrations" }
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  get 'portfolio', to: 'users#portfolio'

  get 'search_stock', to: 'stocks#search'

  resources :user_stocks, only: [:create, :destroy]

  resources :users, only: [:show]

  resources :friendships

  get 'friends', to: 'users#friends'

  post 'add_friend', to: 'users#add_friend'

  get 'search_friend', to: 'users#search'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
    belongs_to :user
    belongs_to :friend, :class_name => 'User'
end

app/models/stock.rb
class Stock < ApplicationRecord
    has_many :user_stocks
    has_many :users, through: :user_stocks

    def self.find_by_ticker(ticker_symbol)
        where(ticker: ticker_symbol).first
    end
     
    def self.new_from_lookup(ticker_symbol)
        begin
            client = IEX::Api::Client.new(publishable_token: 'pk_c3719aaa1dfc479e889055c9aa776ae1')
            looked_up_stock = client.quote(ticker_symbol)
            new(name: looked_up_stock.company_name,
                ticker: looked_up_stock.symbol, last_price: looked_up_stock.latest_price)
        rescue Exception => e
            return nil
        end
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :user_stocks
  has_many :stocks, through: :user_stocks
  has_many :friendships
  has_many :friends, through: :friendships

  def get_full_name
    return "#{first_name} #{last_name}".strip if (first_name || last_name)
    "Anonymous"
  end
  def stock_already_added?(ticker_symbol) 
    stock = Stock.find_by_ticker(ticker_symbol)
    return false unless stock
    user_stocks.where(stock_id: stock.id).exists?
  end

  def under_limit?
    (user_stocks.count < 10)
  end

  def can_add_stock?(ticker_symbol)
    (!stock_already_added?(ticker_symbol) && under_limit?)
  end

  def self.search(param)
    param.strip!
    param.downcase!
    send_back = (first_name_matches(param) + last_name_matches(param) + email_matches(param)).uniq
    return nil unless send_back
    send_back
  end

  def self.first_name_matches(param)
    matches("first_name", param)
  end

  def self.last_name_matches(param)
    matches("last_name", param)
  end

  def self.email_matches(param)
    matches("email", param)
  end

  def self.matches(field_name, param)
    where("#{field_name} like?", "%#{param}%")
  end

  def except_current_user(users)
    users.reject {
      |user| user.id == self.id
    }
  end

  def not_friends_with?(friend_id)
    friendships.where(friend_id: friend_id).count < 1
  end
end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery prepend: true
    before_action :authenticate_user!
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
    def destroy
        @friendship = current_user.friendships.where(friend_id: params[:id]).first
        @friendship.destroy
        flash[:success] = "You are no longer friends."
        redirect_to friends_path
    end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
    def search
        if params[:stock].blank?
            flash.now[:danger] = "You entered an empty string."
        else
            @stock = Stock.new_from_lookup(params[:stock])
            flash.now[:danger] = "You have entered an incorrect symbol." unless @stock
        end 
        respond_to do |format|
            format.js { render partial: 'users/result' }
        end
    end
end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController
    def create
        stock = Stock.find_by_ticker(params[:stock_ticker])
        if stock.blank?
            stock = Stock.new_from_lookup(params[:stock_ticker])
            stock.save
        end
        @user_stocks = UserStock.create(user: current_user, stock: stock)
        flash[:success] = "#{@user_stocks.stock.name} was succesfully added."
        redirect_to portfolio_path
    end

    def destroy
       stock = Stock.find(params[:id])
       @user_stock = UserStock.where(user_id: current_user.id, stock_id: stock.id).first
       @user_stock.destroy
       flash[:success] = "You have successfully deleted #{stock.name} from your portfolio."
       redirect_to portfolio_path
    end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
    before_action :configure_permitted_parameters

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
        devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def portfolio
        @user = current_user
        @user_stocks = current_user.stocks
    end

    def friends
        @friendships = current_user.friends
    end

    def search
        if params[:search_param].blank?
            flash.now[:danger] = "You entered an empty string."
        else
            @users = User.search(params[:search_param])
            @users = current_user.except_current_user(@users)
            flash.now[:danger] = "No users were found." if @users.blank?
        end 
        respond_to do |format|
            format.js { render partial: 'friends/result' }
        end
    end
    
    def add_friend
        @friend = User.find(params[:friend])
        current_user.friendships.build(friend_id: @friend.id)

        if current_user.save
            flash[:success] = "You have added #{@friend.get_full_name} as a friend."
        else
            flash[:danger] = "Something went wrong."
        end
        redirect_to friends_path
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def index
        
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/friends/_lookup.html.erb
<h3> Look up a Friend. </h3>
<div id="stock-lookup">
    <%= form_tag search_friend_path, remote: true,  method: :get, id: "friend-lookup-form" do %>
        <div class="form-group row no-padding text-center col-md-12">
            <div class="col-md-10">
                <%= text_field_tag :search_param, params[:search_param], 
                                    placeholder: "Friend's name or email", 
                                    autofocus: true, 
                                    class: "form-control search-box input-lg" %>
            </div>
            <div class ="col-md-2">
                <%= button_tag(type: :submit, class: "btn btn-lg btn-success") do %>
                <i class="glyphicon glyphicon-user"></i> Look up a Friend
                <% end  %>
            </div>
        </div>
    <% end %>
</div>

app/views/friends/_result.html.erb
<% if params[:action] == 'search' %>
    <div class="results-block">
        <%= bootstrap_flash %>
    </div>
<% end %>
<% if @users and @users.size > 0 %>
    <div class="well results-block col-md-8" id="friend-lookup-results">
        <table class="search-results-table col-md-12">
            <tbody>
                <% @users.each do |user| %>
                    <tr>
                        <td><strong>Name: </strong><%= user.get_full_name %></td>
                        <td><strong>Email: </strong><%= user.email %></td>
                        <td><%= link_to  "View Profile", "#", class: "btn btn-xs btn-primary" %>
                        <% if current_user.not_friends_with?(user.id) %>
                            <%= link_to  "Add as a friend", add_friend_path(user: current_user, friend: user), class: "btn btn-xs btn-primary", method: :post %>
                        <% else %>
                            <span class="label label-primary">You are already friends. </span>
                        <% end %>
                        </td>
                    </tr>
                <% end %>
            </tbody>
        </table>
    </div>
<% end %>

app/views/friends/_result.js.erb
$('#results').html("<%= j (render 'friends/result.html') %>");

app/views/layouts/_navigation.html.erb
<div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <%= link_to  "Stock Tracker", root_path, class: "navbar-brand" %>
        <% if current_user %>
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav col-md-6">
            <li><%= link_to "My Portfolio", portfolio_path  %></li>
            <li><%= link_to "Edit my Profile", edit_user_registration_path  %></li>
            <li><%= link_to "My Friends", friends_path  %></li>
          </ul>
          <ul class="nav navbar-right col-md-4">
            <li class="col-md-8 user-name text-right"> 
              <i class="glyphicon glyphicon-user"></i>
              <%= current_user.get_full_name.present? ? current_user.get_full_name : current_user.email %>
            </li>
            <li class="col-md-4 logout"> <%= link_to  "Logout", destroy_user_session_path, method: :delete, class: "btn btn-danger btn-md" %>
            </li>
          </ul>
        </div>
        <% end %>
      </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    

    <title><%= content_for?(:title) ? yield(:title) : "StockTracker" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%
=begin%>
 <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %> 
<%
=end%>

    <%= javascript_include_tag "application" %>
    
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap-theme.css">

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <%= render  "layouts/navigation" %>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Kantor 2019</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/stocks/_list.html.erb
<table class="table table-striped">
    <thead>
        <tr>
            <th>Name</th>
            <th>Ticker Symbol</th>
            <th>Current Price</th>
            <% if @user.id == current_user.id %>
                <th>Actions </th>
            <% end %>
        </tr>
    </thead>

    <tbody>
        <% @user_stocks.each do |stock| %>
            <tr>
                <td><%= stock.name %></td>
                <td><%= stock.ticker %></td>
                <td><%= stock.last_price %></td>
            
            <% if @user.id == current_user.id %>
                <td><%= link_to  "Delete Stock From Portfolio", user_stock_path(stock), method: :delete, 
                                                                        data: {confirm: "Are you sure?"}, 
                                                                        class: "btn btn-xs btn-danger" %>
                </td>
            <% end %>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/users/_result.html.erb
<% if params[:action] == 'search' %>
    <div class="results-block">
        <%= bootstrap_flash %>
    </div>
<% end %>
<% if @stock %>
    <div class="well results-block">
        <strong>Symbol: </strong><%= @stock.ticker %>
        <strong>Name: </strong><%= @stock.name %>
        <strong>Price: </strong><%= @stock.last_price %>
        <% if current_user.can_add_stock?(@stock.ticker) %>
            <%= link_to  "Add to my Watchlist", user_stocks_path(user: current_user, stock_ticker: @stock.ticker), class: "btn btn-xs btn-success", method: :post %>
        <% else %>
            <span class="label label-default">
                Stock cannot be added because you have already added 
                <% if current_user.stock_already_added?(@stock.ticker) %>
                    this stock.
                <% else %>
                    <% if !current_user.under_limit? %>
                        10 stocks.
                    <% end %>
                <% end %>
            </span>
        <% end %>
    </div>
<% end %>  

app/views/users/_result.js.erb
$('#results').html("<%= j (render 'users/result.html') %>");

app/views/users/friends.html.erb
<h1>Friends list</h1>

<%= render  "friends/lookup" %>
<div id="results">
    <%= render  "result" %>
</div>

<% if (@friendships.size > 0) %>
    <table class="table table-striped">
        <thead>
            <tr>
                <th class="page-header" colspan="3">
                    <h2>My Friends</h2>
                </th>
            </tr>
            <tr>
                <th>Name</th>
                <th>Email</th>
                <th>Actions</th>
            </tr>
        </thead>

        <tbody>
            <% @friendships.each do |friend| %>
                <tr>
                    <td><%= friend.get_full_name %></td>
                    <td><%= friend.email %></td>
                    <td><%= link_to  "#{friend.get_full_name}'s Profile", user_path(friend), class: "btn btn-xs btn-primary" %>
                        <%= link_to  "Remove #{friend.get_full_name}", friendship_path(friend), method: :delete, 
                                                                            data: {confirm: "Are you sure?"}, 
                                                                            class: "btn btn-xs btn-danger" %>
                    </td>
                </tr>
            <% end %>
        </tbody>
    </table>
<% else %>
    <div class="row col-md-12 ">
        <p class="lead"> You don't have any friends yet. Try adding some! </p>
    </div>
<% end %>

app/views/users/portfolio.html.erb
<h1> This is your portfolio </h1>

<h3> Look up a stock. </h3>
<div id="stock-lookup">
    <%= form_tag search_stock_path, remote: true,  method: :get, id: "stock-lookup-form" do %>
        <div class="form-group row no-padding text-center col-md-12">
            <div class="col-md-10">
                <%= text_field_tag :stock, params[:stock], 
                                    placeholder: "Stock ticker symbol", 
                                    autofocus: true, 
                                    class: "form-control search-box input-lg" %>
            </div>
            <div class ="col-md-2">
                <%= button_tag(type: :submit, class: "btn btn-lg btn-success") do %>
                <i class="glyphicon glyphicon-search"></i> Look up a stock
                <% end  %>
            </div>
        </div>
    <% end %>
</div>
<div id="results">
    <%= render  "result" %>
</div>
<div id="stock-list"> 
    <%= render  "stocks/list" %>
</div>

app/views/welcome/index.html.erb
<h1> Stock tracker web app </h1>